version: '3.7'
services:
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus.rule.yml:/etc/prometheus/prometheus.rule.yml
    ports:
      - "9090:9090"
    networks:
      - prom_net
  grafana:
    image: grafana/grafana-enterprise
    depends_on:
      prometheus:
        condition: service_started
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD:password
    volumes:
      - grafana_data:/var/lib/grafana
    ports:
      - "3000:3000"
    networks:
      - prom_net
  node-exporter:
    image: prom/node-exporter
    depends_on:
      prometheus:
        condition: service_started
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    ports:
      - "9100:9100"
    networks:
      - prom_net
networks:
  prom_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.30.0.0/24"
volumes:
  grafana_data:
